on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  build_and_package:
    name: BUILD-JOB
    runs-on: ubuntu-slim

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Install Dependencies
        run: npm install

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: TEST
        run: echo "Code is tested!"

      - name: Artifact upload
        uses: actions/upload-artifact@v7
        with:
          name: artifact-7
          path: |
            package*

      - name: Deploy
        run: echo "Code is deployed"
